### ISSUE TITLE
Unable to Track Version from Terminal and Module Import Failure

### ISSUE THREAD

**Issue by lshpaner** [lshpaner/eda_toolkit#57]
## Description

When attempting to track the version of the eda_toolkit library from the terminal, an error occurs due to a missing module (`IPython`). The import fails, making it impossible to proceed with version tracking or usage.

### Steps to Reproduce

1. Open a terminal and activate the virtual environment.
2. Start a Python interactive session (python).

```python
import eda_toolkit
```

The following error is raised:

```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lshpaner/Python_Projects/circ_milan/venv_circ_311/lib/python3.11/site-packages/eda_toolkit/__init__.py", line 42, in <module>
    from .main import *
  File "/home/lshpaner/Python_Projects/circ_milan/venv_circ_311/lib/python3.11/site-packages/eda_toolkit/main.py", line 11, in <module>
    from IPython.display import display
ModuleNotFoundError: No module named 'IPython'
```

The library should import without errors, and the version should be retrievable using:

```python
eda_toolkit.__version__
```

### Root Cause Analysis

The error indicates that the IPython module is a dependency but is not installed in the current environment. This dependency is critical for the library to function, particularly for displaying outputs.

### Proposed Solutions

1. Update Installation Requirements: Ensure that IPython is listed as a required dependency in the `eda_toolkit` package's pyproject.toml`.

  ```python
  install_requires=[
      "IPython>=7.0.0",
      ...
  ]
  ```

2. Remove Necessity for Using`IPython` Display:

  ```python
  from IPython.display import display
  ```

This line supports the `display(crosstab_df)` statement inside the `stacked_crosstab_plot` function. To resolve the issue:

- Remove the import for `IPython.display`.
- Replace the line `display(crosstab_df)` with an alternative approach, such as using `print()` or returning the DataFrame explicitly.

This way, the library would no longer require `IPython`, reducing overhead and preventing import issues.

3. Update the installation guide to specify the required dependencies or provide instructions for ensuring a complete setup.

**Comment by lshpaner** [comment]
Resolved via https://github.com/lshpaner/eda_toolkit/pull/68
